AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    f0e8f648-ef12-4851-b2e7-fa3d05b500f7:
      size:
        width: 60
        height: 60
      position:
        x: 130
        'y': 90
      z: 0
      embeds: []
    23b506b1-4503-432c-a5a3-f11af3218588:
      size:
        width: 60
        height: 60
      position:
        x: 250
        'y': 90
      z: 0
      embeds: []
      isassociatedwith:
        - f0e8f648-ef12-4851-b2e7-fa3d05b500f7
Mappings:
  RegionMap:
    us-east-2b:
      PublicSubnet: subnet-0335acd13c99ee000
      PrivateSubnet: subnet-0ef22cd9fd0521d15
    us-east-2a:
      PublicSubnet: subnet-0b8cf0ce4c6171ea3
      PrivateSubnet: subnet-0f1bf8968458cf81e
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: 'Enter t2.micro, m1.small, or m1.large. Default is t2.micro.'
  ImageIdParameter:
    Type: String
    Default: ami-010e92adc17c59579
    Description: Enter AMI ID.
  TargetGroupARNsParameter:
    Type: String
    Default: >-
      arn:aws:elasticloadbalancing:us-east-2:606297394529:targetgroup/tg-ohio-test-mediawiki/8e859200890611b7
    Description: Enter Target Group ARN.
Resources:
  ASLC5CFAJ:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f0e8f648-ef12-4851-b2e7-fa3d05b500f7
    Properties:
      ImageId:
        Ref: ImageIdParameter
      InstanceType:
        Ref: InstanceTypeParameter
      LaunchConfigurationName: MediaWikiApplication
      SecurityGroups:
        - sg-00b765b003a0aec03
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: '10'
            Iops: '100'
  ASASG1UQQ2:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      LaunchConfigurationName: !Ref ASLC5CFAJ
      AutoScalingGroupName: asg-ohio-mediawiki
      VPCZoneIdentifier:
        - !FindInMap 
          - RegionMap
          - us-east-2b
          - PublicSubnet
        - !FindInMap 
          - RegionMap
          - us-east-2a
          - PublicSubnet
      DesiredCapacity: 2
      HealthCheckGracePeriod: 100
      MaxSize: 3
      MinSize: 2
      TargetGroupARNs:
        - Ref: TargetGroupARNsParameter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 23b506b1-4503-432c-a5a3-f11af3218588
