- name: Launch instance
  ec2:
    key_name: "{{ key_pair }}"
    group_id: "{{ application_security_group[0] }}"
    instance_type: t2.micro
    image: ami-0b500ef59d8335eee
    wait: true
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ public_subnets[0] }}"
    assign_public_ip: yes
    instance_tags:
      Name: MediaWikiServer
    count_tag:
      Name: MediaWikiServer
    exact_count: 1
  register: ec2
- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items: "{{ ec2.tagged_instances }}"
- debug:
    msg: "{{ ec2 }}"
- name: sleep for 2 mins and continue with play
  wait_for: timeout=10
- name: save precious value
  set_fact:
    instanceid: "{{ ec2.tagged_instances[0].id }}"

