---
# tasks file for mediawiki
- elb_target_group:
    name: tg-ohio-test-mediawiki
    protocol: http
    port: 80
    vpc_id: vpc-08a02491160e8536d
    region: us-east-2
    state: present
  register: target
- debug:
    msg: "{{ target }}"
- elb_application_lb:
    name: myelb
    region: us-east-2
    security_groups:
      - sg-00b765b003a0aec03
    subnets:
      - subnet-0b8cf0ce4c6171ea3
      - subnet-0335acd13c99ee000
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupName: tg-ohio-test-mediawiki
    state: present
  register: app_lb
- debug:
    msg: "{{ app_lb }}"
- rds:
    command: create
    instance_name: mediawikidbinstance-test
    db_engine: mariadb
    db_name: mediawikidb_test
    size: 20
    instance_type: db.t2.micro
    username: admin
    password: mediawiki2019
    vpc_security_groups: sg-0a3d7a9b9ca5bd3de
    subnet: db-subnet-group-ohio-t-mediawiki
    region: us-east-2
    tags:
      Environment: test
      Application: mediawiki
    wait: yes
    wait_timeout: 300
- rds:
    command: facts
    instance_name: mediawikidbinstance-test
    region: us-east-2
  register: rds
- debug:
    msg: "The new db endpoint is {{ rds.instance.endpoint }}"
- name: Create a new database with name 'wikidatabase'
  mysql_db:
    name: wikidatabase
    state: present
    login_host: "{{ rds.instance.endpoint }}"
    login_user: admin
    login_password: mediawiki2019
- mysql_user:
    name: wiki
    password: mediawiki2019
    priv: '*.*:select,update,delete,insert,create,drop,index,alter,lock tables,execute,create temporary tables,execute,trigger,create view,show view,event'
    state: present
    login_host: "{{ rds.instance.endpoint }}"
    login_user: admin
    login_password: mediawiki2019
- template:
    src: LocalSettings.php
    dest: /home/ec2-user/
- name: Launch instance
  ec2:
    key_name: mediawiki
    group: launch-wizard-1
    instance_type: t2.micro
    image: ami-0b500ef59d8335eee
    wait: true
    region: us-east-2
    vpc_subnet_id: subnet-0b8cf0ce4c6171ea3
    assign_public_ip: yes
    instance_tags:
      Name: MediaWikiServer
    count_tag:
      Name: MediaWikiServer
    exact_count: 2
  register: ec2
- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items: "{{ ec2.tagged_instances }}"
- debug:
    msg: "{{ item.private_ip }}"
  with_items: "{{ ec2.tagged_instances }}"
#- name: Wait for SSH to come up
#  delegate_to: "{{ item.private_ip }}"
#  wait_for_connection:
#    delay: 60
#    timeout: 320
#  with_items: "{{ ec2.instances }}"
- name: sleep for 150 seconds and continue with play
  wait_for: timeout=60
