---
# tasks file for mediawiki
- elb_target_group:
    name: tg-ohio-test-mediawiki
    protocol: http
    port: 80
    vpc_id: "{{ mediawiki_vpc_id }}"
    region: "{{ aws_region }}"
    state: present
  register: target
- debug:
    msg: "{{ target }}"
- elb_application_lb:
    name: myelb
    region: "{{ aws_region }}"
    security_groups: "{{ application_security_group[0] }}"
    subnets: "{{ public_subnets }}"
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupName: tg-ohio-test-mediawiki
    state: present
  register: app_lb
- debug:
    msg: "{{ app_lb }}"
- rds:
    command: create
    instance_name: mediawikidbinstance-test
    db_engine: mariadb
    db_name: mediawikidb_test
    size: 20
    instance_type: db.t2.micro
    username: admin
    password: "{{ db_password }}"
    vpc_security_groups: "{{ database_security_group[0] }}"
    subnet: db-subnet-group-ohio-t-mediawiki
    region: "{{ aws_region }}"
    tags:
      Environment: test
      Application: mediawiki
    wait: yes
    wait_timeout: 300
- rds:
    command: facts
    instance_name: mediawikidbinstance-test
    region: "{{ aws_region }}"
  register: rds
- debug:
    msg: "The new db endpoint is {{ rds.instance.endpoint }}"
- name: Create a new database with name 'wikidatabase'
  mysql_db:
    name: wikidatabase
    state: present
    login_host: "{{ rds.instance.endpoint }}"
    login_user: admin
    login_password: "{{ db_password }}"
- mysql_user:
    name: wiki
    password: "{{ db_password }}"
    priv: '*.*:select,update,delete,insert,create,drop,index,alter,lock tables,execute,create temporary tables,execute,trigger,create view,show view,event'
    state: present
    login_host: "{{ rds.instance.endpoint }}"
    login_user: admin
    login_password: "{{ db_password }}"
- template:
    src: LocalSettings.php
    dest: /home/ec2-user/
- name: Launch instance
  ec2:
    key_name: "{{ key_pair }}"
    group_id: "{{ application_security_group[0] }}"
    instance_type: t2.micro
    image: ami-0b500ef59d8335eee
    wait: true
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ public_subnets[0] }}"
    assign_public_ip: yes
    instance_tags:
      Name: MediaWikiServer
    count_tag:
      Name: MediaWikiServer
    exact_count: 1
  register: ec2
- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items: "{{ ec2.tagged_instances }}"
- debug:
    msg: "{{ ec2 }}"
- name: sleep for 2 mins and continue with play
  wait_for: timeout=120
- name: save precious value
  set_fact: 
    lbarn: "{{ target.target_group_arn }}"
    instanceid: "{{ ec2.tagged_instances[0].id }}"
